### ISSUE TITLE
Console Sends Warning

### ISSUE THREAD

**Issue by MadEste** [aadijain725/AlgoWiz#35]
https://github.com/aadijain725/AlgoWiz/blob/5cea22f46d0971fff433fd2889be719c23245375/algowiz-app/src/components/HomePageTopicTab.js#L25

This is a low priority bug

Console keeps reporting this warning:
console.error
    Warning: Received `true` for a non-boolean attribute `h-100`.
    
    If you want to write it to the DOM, pass a string instead: h-100="true" or h-100={value.toString()}.
        at div
        at /Users/este/Desktop/AlgoWiz/algowiz-app/node_modules/react-bootstrap/cjs/Col.js:22:23
        at div
        at /Users/este/Desktop/AlgoWiz/algowiz-app/node_modules/react-bootstrap/cjs/Row.js:24:23
        at div
        at /Users/este/Desktop/AlgoWiz/algowiz-app/node_modules/react-bootstrap/cjs/Container.js:23:23
        at Router (/Users/este/Desktop/AlgoWiz/algowiz-app/node_modules/react-router/cjs/react-router.js:99:30)
        at BrowserRouter (/Users/este/Desktop/AlgoWiz/algowiz-app/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
        at App

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3521:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)

**Comment by MadEste** [comment]
#58 resolved this issue
