### ISSUE TITLE
Console CSS warning

### ISSUE THREAD

**Issue by MadEste** [aadijain725/AlgoWiz#37]
CSS files need to be cleaned up?
Low priority
Console warning:
index.js:1 Warning: Unsupported style property font-size. Did you mean fontSize?
    at nav
    at http://localhost:3000/static/js/vendors~main.chunk.js:8996:22
    at http://localhost:3000/static/js/vendors~main.chunk.js:13476:96
    at TabContainer (http://localhost:3000/static/js/vendors~main.chunk.js:15263:96)
    at Tabs (http://localhost:3000/static/js/vendors~main.chunk.js:15595:96)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at div
    at HomePageTopicsTabs (http://localhost:3000/static/js/main.chunk.js:1151:1)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at HomePage (http://localhost:3000/static/js/main.chunk.js:543:1)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:49346:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:49548:29)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:48981:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:48601:35)
    at App

**Comment by MadEste** [comment]
#58 resolved this issue
