### ISSUE TITLE
Dynamic elements need unique key

### ISSUE THREAD

**Issue by MadEste** [aadijain725/AlgoWiz#38]
Each dynamically rendered component/element needs a unique key!

Low Priority

index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `HomePageTopicsTab`. See https://reactjs.org/link/warning-keys for more information.
    at HomePageTopicsTab (http://localhost:3000/static/js/main.chunk.js:871:1)
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:50505:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11566:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:15412:24
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:15328:23
    at TabContainer (http://localhost:3000/static/js/vendors~main.chunk.js:15263:96)
    at Tabs (http://localhost:3000/static/js/vendors~main.chunk.js:15595:96)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at div
    at HomePageTopicsTabs (http://localhost:3000/static/js/main.chunk.js:1151:1)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at HomePage (http://localhost:3000/static/js/main.chunk.js:543:1)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:49346:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:49548:29)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10733:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:14815:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:10930:23
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:48981:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:48601:35)
    at App

**Comment by MadEste** [comment]
pull request fixed this issue
